default:
  ADMIN_PASSWORD: ""
  BENCHMARK_REQUESTS: false
  DATABASE_URL: ""
  HEROKU_API_TOKEN: ""
  HEROKU_APP_NAME: ""
  HOST: ""
  MODE_DEBUG: true
  MODE_DEBUG_SQL: false
  MODE_PROFILING: false
  PORT: -1
  REDIS_URL: ""
  REQUEST_TIMEOUT: 0
  SENTRY_DSN: ""
  TEST_BROWSER: ""
  TEST_BROWSER_HEADLESS: true
  VENV_SYNTHETIC: false
  WEB_CONCURRENCY: 0


development:
  ADMIN_PASSWORD: "1"
  HOST: "localhost"
  PORT: 8000
  REQUEST_TIMEOUT: 300
  WEB_CONCURRENCY: 1


ci:
  ADMIN_PASSWORD: "1"
  HOST: "localhost"
  PORT: 8000
  REQUEST_TIMEOUT: 100
  SECRET_KEY: "1"
  TEST_BROWSER: "firefox"
  WEB_CONCURRENCY: 2


heroku:
  MODE_DEBUG: false
  REQUEST_TIMEOUT: 10
  VENV_SYNTHETIC: true


docker:
  ADMIN_PASSWORD: "1"
  MODE_DEBUG: false
  REQUEST_TIMEOUT: 10
